#!/bin/bash
EMULATOR_NAME=$1;
EMULATOR_ACTION=$2;
HOME_PATH="/home/$USER"
EMULATOR_PATH="${HOME_PATH}/.${EMULATOR_NAME}"
EMULATOR_BACKUP_PATH="${HOME_PATH}/.${EMULATOR_NAME}.bkp"
EMULATOR_REMOTE_ID=$(gdrive list -m 500 | grep .${EMULATOR_NAME} | grep dir | awk '{print $1}')
echo $EMULATOR_REMOTE_ID
uploadFolder() {
  echo uploading save remote...
  gdrive upload -r $EMULATOR_PATH
}

removeFolder() {
  echo removing save remote ...
  gdrive delete -r $EMULATOR_REMOTE_ID
}

updateFolder() {
  removeFolder
  uploadFolder
}

save() {
  if [ ${#EMULATOR_REMOTE_ID} -ge 1 ]; then
    echo folder found remote
    updateFolder
  else
    echo folder doesnt found remote
    uploadFolder
  fi
}

saveBackup() {
  if [ -d $EMULATOR_PATH ]; then
    echo creating new backup folder...
    cp -r $EMULATOR_PATH $EMULATOR_BACKUP_PATH
  fi
}

createBackup() {
  if [ -d $EMULATOR_BACKUP_PATH ]; then
    echo backup found...
    echo removing backup folder...
    rm -r $EMULATOR_BACKUP_PATH
    saveBackup
  else
    echo backup doesnt found...
    saveBackup
  fi
}

downloadFromRemote() {
  echo downloading from remote...
  gdrive download --path $HOME_PATH -r $EMULATOR_REMOTE_ID --force
  echo Done!
}

selectAction() {
  if [ $EMULATOR_ACTION == save ]; then
    echo saving...
    save
  else 
    echo restoring...
    createBackup
    downloadFromRemote
  fi
}

if [ ${#EMULATOR_NAME} -ge 1 ] && [ ${#EMULATOR_ACTION} -ge 1 ]; then
  selectAction
else
  echo bad request
  echo the parameter should be like: emulator-memory [emulator name] [save / restore]
fi


